### ISSUE TITLE
[QUESTION] Support SQLite?

### ISSUE THREAD

**Issue by ciltocruz** [hjerichen/dbunit#1]
Hello.

I'm starting to do tests that involve databases. For convenience, I'd like not to have a database to test against.

With the old BDUnit you could use "sqlite::memory:" to instantiate an embedded database.

Does this library allow this usage?

**Comment by hjerichen** [comment]
As of Version 0.3.0 you can use SQLiteTestCaseTrait instead of MySQLTestCaseTrait.
Have a look in tests/Integration/SQLiteTest.php

**Comment by ciltocruz** [comment]
Thanks!
